// ── BASE DE DATOS DE ROCAS ─────────────────────────────────────────────────
export const ROCK_DB = {
  huevillo_fino: {
    wi: 10.5,
    ab: 0.18,
    den: 2.55,
    rrN: 0.92,
    name: "Huevillo fino (< 50mm)",
    desc: "Wi ≈ 10.5 | Canto rodado, áridos construcción",
  },
  huevillo_grueso: {
    wi: 12.0,
    ab: 0.22,
    den: 2.65,
    rrN: 0.88,
    name: "Huevillo grueso (50–200mm)",
    desc: "Wi ≈ 12.0 | Rodado, mezcla mineralógica",
  },
  grava_aluvial: {
    wi: 11.0,
    ab: 0.15,
    den: 2.5,
    rrN: 0.95,
    name: "Grava aluvial mixta",
    desc: "Wi ≈ 11.0 | Alto % finos naturales, humedad frecuente",
  },
  bolones_rio: {
    wi: 13.5,
    ab: 0.28,
    den: 2.7,
    rrN: 0.85,
    name: "Bolones de río (> 200mm)",
    desc: "Wi ≈ 13.5 | Requiere scalper o mandíbula grande",
  },
  andesita: {
    wi: 16.0,
    ab: 0.32,
    den: 2.65,
    rrN: 0.78,
    name: "Andesita",
    desc: "Wi ≈ 16.0 | Abrasión media-alta",
  },
  granito: {
    wi: 15.5,
    ab: 0.28,
    den: 2.7,
    rrN: 0.8,
    name: "Granito",
    desc: "Wi ≈ 15.5 | Abrasión media",
  },
  basalto: {
    wi: 17.0,
    ab: 0.35,
    den: 2.9,
    rrN: 0.75,
    name: "Basalto",
    desc: "Wi ≈ 17.0 | Abrasión alta",
  },
  diorita: {
    wi: 15.0,
    ab: 0.3,
    den: 2.8,
    rrN: 0.79,
    name: "Diorita",
    desc: "Wi ≈ 15.0 | Abrasión media",
  },
  gabro: {
    wi: 13.0,
    ab: 0.25,
    den: 2.95,
    rrN: 0.81,
    name: "Gabro",
    desc: "Wi ≈ 13.0 | Abrasión media",
  },
  caliza: {
    wi: 11.2,
    ab: 0.12,
    den: 2.6,
    rrN: 1.05,
    name: "Caliza",
    desc: "Wi ≈ 11.2 | Baja abrasión",
  },
  arenisca: {
    wi: 9.5,
    ab: 0.08,
    den: 2.3,
    rrN: 1.15,
    name: "Arenisca",
    desc: "Wi ≈ 9.5  | Muy baja abrasión",
  },
  dolomita: {
    wi: 11.5,
    ab: 0.14,
    den: 2.85,
    rrN: 1.02,
    name: "Dolomita",
    desc: "Wi ≈ 11.5 | Baja abrasión",
  },
  cuarcita: {
    wi: 19.5,
    ab: 0.45,
    den: 2.65,
    rrN: 0.7,
    name: "Cuarcita",
    desc: "Wi ≈ 19.5 | Muy alta abrasión",
  },
  porfido: {
    wi: 16.0,
    ab: 0.3,
    den: 2.72,
    rrN: 0.82,
    name: "Pórfido cuprífero",
    desc: "Wi ≈ 16.0 | Abrasión media",
  },
  cobre_ox: {
    wi: 10.5,
    ab: 0.15,
    den: 2.5,
    rrN: 0.95,
    name: "Mineral oxidado cobre",
    desc: "Wi ≈ 10.5 | Baja abrasión",
  },
  magnetita: {
    wi: 10.0,
    ab: 0.2,
    den: 4.9,
    rrN: 0.88,
    name: "Magnetita",
    desc: "Wi ≈ 10.0 | Alta densidad",
  },
  hematita: {
    wi: 12.5,
    ab: 0.25,
    den: 4.8,
    rrN: 0.85,
    name: "Hematita",
    desc: "Wi ≈ 12.5 | Alta densidad",
  },
  oro_cuarzo: {
    wi: 15.0,
    ab: 0.4,
    den: 2.8,
    rrN: 0.77,
    name: "Oro en cuarzo",
    desc: "Wi ≈ 15.0 | Abrasión alta",
  },
  caliche: {
    wi: 7.0,
    ab: 0.05,
    den: 2.1,
    rrN: 1.2,
    name: "Caliche",
    desc: "Wi ≈ 7.0  | Muy blanda",
  },
  hormigon_demolicion: {
    wi: 9.0,
    ab: 0.08,
    den: 2.3,
    rrN: 1.15,
    name: "Hormigón de demolición",
    desc: "Wi ≈ 9.0  | Reciclaje C&D, baja abrasión",
  },
  desconocida: {
    wi: 13.0,
    ab: 0.2,
    den: 2.7,
    rrN: 0.85,
    name: "Roca desconocida",
    desc: "Valores promedio estimados",
  },
};

export const ROCK_CATS = {
  aridos: ["huevillo_fino", "huevillo_grueso", "grava_aluvial", "bolones_rio"],
  mineria: ["porfido", "cobre_ox", "magnetita", "oro_cuarzo"],
  roca_dura: ["andesita", "granito", "basalto", "cuarcita"],
  roca_blanda: ["caliza", "caliche", "arenisca", "dolomita", "hormigon_demolicion"],
};

// ── CATÁLOGO DE EQUIPOS (FALLBACK LOCAL) ──────────────────────────────────
// TODO: eliminar cuando el endpoint /equipment esté estable en producción.
// El componente App lo sobreescribe con datos de Supabase al montarse.
export const EQ_LOCAL = {
  jaw: [
    {
      brand: "Terex Finlay",
      model: "J-960",
      palanca: "doble",
      rpm: 320,
      feedMm: 580,
      cssR: [40, 140],
      capR: [80, 200],
      notes: "Compacta, orugas",
    },
    {
      brand: "Terex Finlay",
      model: "J-1160",
      palanca: "doble",
      rpm: 300,
      feedMm: 780,
      cssR: [45, 160],
      capR: [150, 280],
      notes: "Orugas, C9.3 ACERT",
    },
    {
      brand: "Terex Finlay",
      model: "J-1175",
      palanca: "doble",
      rpm: 290,
      feedMm: 790,
      cssR: [50, 175],
      capR: [200, 350],
      notes: "Orugas, C13 ACERT",
    },
    {
      brand: "Terex Finlay",
      model: "J-1280",
      palanca: "doble",
      rpm: 270,
      feedMm: 1070,
      cssR: [75, 175],
      capR: [250, 400],
      notes: "Orugas, alta capacidad",
    },
    {
      brand: "Terex Finlay",
      model: "J-1480",
      palanca: "simple",
      rpm: 250,
      feedMm: 1400,
      cssR: [100, 200],
      capR: [400, 600],
      notes: "Orugas, gran formato",
    },
    {
      brand: "Powerscreen",
      model: "Premiertrak 600",
      palanca: "doble",
      rpm: 310,
      feedMm: 600,
      cssR: [40, 150],
      capR: [100, 220],
      notes: "Compacta, orugas",
    },
    {
      brand: "Powerscreen",
      model: "Premiertrak 1180",
      palanca: "doble",
      rpm: 275,
      feedMm: 1070,
      cssR: [75, 175],
      capR: [200, 400],
      notes: "Accionamiento directo",
    },
    {
      brand: "Powerscreen",
      model: "Premiertrak 1300",
      palanca: "simple",
      rpm: 260,
      feedMm: 1100,
      cssR: [75, 175],
      capR: [250, 450],
      notes: "Alta capacidad",
    },
    {
      brand: "Kleemann",
      model: "MC 100 Ri EVO",
      palanca: "doble",
      rpm: 305,
      feedMm: 760,
      cssR: [50, 150],
      capR: [150, 280],
      notes: "Diesel-eléctrico",
    },
    {
      brand: "Kleemann",
      model: "MC 110 Ri EVO",
      palanca: "doble",
      rpm: 290,
      feedMm: 950,
      cssR: [60, 160],
      capR: [200, 380],
      notes: "Diesel-eléctrico",
    },
    {
      brand: "Kleemann",
      model: "MC 120 Zi EVO",
      palanca: "simple",
      rpm: 265,
      feedMm: 1200,
      cssR: [80, 180],
      capR: [300, 500],
      notes: "Diesel-eléctrico",
    },
    {
      brand: "Sandvik",
      model: "UJ310",
      palanca: "doble",
      rpm: 300,
      feedMm: 820,
      cssR: [50, 160],
      capR: [150, 280],
      notes: "Orugas",
    },
    {
      brand: "Sandvik",
      model: "UJ440i",
      palanca: "simple",
      rpm: 265,
      feedMm: 1100,
      cssR: [65, 200],
      capR: [200, 450],
      notes: "Radio remoto incluido",
    },
    {
      brand: "Metso Outotec",
      model: "LT106",
      palanca: "doble",
      rpm: 290,
      feedMm: 900,
      cssR: [55, 160],
      capR: [150, 300],
      notes: "Orugas sobre chasis",
    },
    {
      brand: "Metso Outotec",
      model: "LT120",
      palanca: "doble",
      rpm: 275,
      feedMm: 1100,
      cssR: [65, 180],
      capR: [200, 400],
      notes: "Orugas, alta producción",
    },
    {
      brand: "Metso Outotec",
      model: "LT130E",
      palanca: "simple",
      rpm: 255,
      feedMm: 1200,
      cssR: [75, 200],
      capR: [250, 500],
      notes: "Eléctrico, gran capacidad",
    },
    {
      brand: "Astec",
      model: "GT125",
      palanca: "doble",
      rpm: 310,
      feedMm: 760,
      cssR: [45, 150],
      capR: [120, 250],
      notes: "Orugas, compacta",
    },
    {
      brand: "Astec",
      model: "GT165",
      palanca: "doble",
      rpm: 285,
      feedMm: 1050,
      cssR: [65, 175],
      capR: [200, 380],
      notes: "Orugas, estándar",
    },
  ],
  cone: [
    {
      brand: "Terex Finlay",
      model: "C-1540",
      rpm: 280,
      feedMm: 215,
      cssR: [10, 44],
      capR: [150, 300],
      notes: "Cono secundario estándar",
    },
    {
      brand: "Terex Finlay",
      model: "C-1545",
      rpm: 285,
      feedMm: 240,
      cssR: [10, 48],
      capR: [160, 320],
      notes: "Cono alta eficiencia",
    },
    {
      brand: "Terex Finlay",
      model: "C-1550",
      rpm: 290,
      feedMm: 280,
      cssR: [10, 50],
      capR: [180, 370],
      notes: "Alta capacidad, orugas",
    },
    {
      brand: "Terex Finlay",
      model: "C-1554",
      rpm: 295,
      feedMm: 280,
      cssR: [8, 50],
      capR: [200, 400],
      notes: "Recorrido largo, alto rendimiento",
    },
    {
      brand: "Powerscreen",
      model: "Maxtrak 1000",
      rpm: 300,
      feedMm: 130,
      cssR: [8, 38],
      capR: [80, 200],
      notes: "Compacto, orugas",
    },
    {
      brand: "Powerscreen",
      model: "Maxtrak 1150",
      rpm: 285,
      feedMm: 185,
      cssR: [10, 44],
      capR: [130, 280],
      notes: "Autónomo sobre orugas",
    },
    {
      brand: "Powerscreen",
      model: "Maxtrak 1300",
      rpm: 278,
      feedMm: 220,
      cssR: [10, 48],
      capR: [180, 380],
      notes: "Alta capacidad",
    },
    {
      brand: "Sandvik",
      model: "QH331",
      rpm: 310,
      feedMm: 185,
      cssR: [6, 38],
      capR: [100, 240],
      notes: "CH430 Hydrocone",
    },
    {
      brand: "Sandvik",
      model: "QH332",
      rpm: 310,
      feedMm: 185,
      cssR: [6, 38],
      capR: [120, 260],
      notes: "CH430 Hydrocone",
    },
    {
      brand: "Sandvik",
      model: "QH441",
      rpm: 290,
      feedMm: 275,
      cssR: [8, 45],
      capR: [180, 400],
      notes: "CH660 Hydrocone",
    },
    {
      brand: "Kleemann",
      model: "MCO 9i S EVO",
      rpm: 315,
      feedMm: 150,
      cssR: [8, 32],
      capR: [90, 200],
      notes: "Diesel-eléctrico",
    },
    {
      brand: "Kleemann",
      model: "MCO 11i EVO",
      rpm: 298,
      feedMm: 185,
      cssR: [8, 44],
      capR: [130, 300],
      notes: "Diesel-eléctrico",
    },
    {
      brand: "Kleemann",
      model: "MCO 13i EVO",
      rpm: 285,
      feedMm: 225,
      cssR: [10, 48],
      capR: [180, 400],
      notes: "",
    },
    {
      brand: "Metso Outotec",
      model: "LT200HPS",
      rpm: 280,
      feedMm: 215,
      cssR: [8, 44],
      capR: [140, 300],
      notes: "Orugas, cono HP",
    },
    {
      brand: "Metso Outotec",
      model: "LT300HPS",
      rpm: 270,
      feedMm: 270,
      cssR: [10, 50],
      capR: [200, 450],
      notes: "Orugas, gran capacidad",
    },
    {
      brand: "Astec",
      model: "GT440",
      rpm: 290,
      feedMm: 190,
      cssR: [8, 44],
      capR: [130, 280],
      notes: "Orugas",
    },
    {
      brand: "Astec",
      model: "GT550",
      rpm: 278,
      feedMm: 230,
      cssR: [10, 50],
      capR: [180, 380],
      notes: "Orugas, alta capacidad",
    },
  ],
  hsi: [
    {
      brand: "Terex Finlay",
      model: "I-110RS",
      feedMm: 750,
      capR: [130, 250],
      notes: "Primario/secundario, orugas",
    },
    {
      brand: "Terex Finlay",
      model: "I-120RS",
      feedMm: 850,
      capR: [160, 300],
      notes: "Con seleccionadora integrada",
    },
    {
      brand: "Terex Finlay",
      model: "I-140RS",
      feedMm: 900,
      capR: [250, 400],
      notes: "Alta capacidad, orugas",
    },
    {
      brand: "Terex Finlay",
      model: "I-1312RS",
      feedMm: 1100,
      capR: [300, 500],
      notes: "Primario, roca blanda-media",
    },
    {
      brand: "Powerscreen",
      model: "Trakpactor 260",
      feedMm: 800,
      capR: [150, 280],
      notes: "Orugas",
    },
    {
      brand: "Powerscreen",
      model: "Trakpactor 320",
      feedMm: 900,
      capR: [200, 350],
      notes: "Orugas",
    },
    {
      brand: "Powerscreen",
      model: "Trakpactor 550SR",
      feedMm: 1100,
      capR: [300, 500],
      notes: "Con seleccionadora integrada",
    },
    {
      brand: "Kleemann",
      model: "MR 110i EVO2",
      feedMm: 1100,
      capR: [200, 380],
      notes: "Diesel-eléctrico",
    },
    {
      brand: "Kleemann",
      model: "MR 130i EVO2",
      feedMm: 1300,
      capR: [300, 500],
      notes: "Diesel-eléctrico",
    },
    {
      brand: "Metso Outotec",
      model: "LT1213S",
      feedMm: 1000,
      capR: [200, 400],
      notes: "Con seleccionadora integrada",
    },
    {
      brand: "Metso Outotec",
      model: "LT1415",
      feedMm: 1100,
      capR: [250, 450],
      notes: "",
    },
    {
      brand: "Sandvik",
      model: "QI341",
      feedMm: 850,
      capR: [160, 300],
      notes: "HSI primario/secundario",
    },
    {
      brand: "Sandvik",
      model: "QI442",
      feedMm: 1000,
      capR: [250, 450],
      notes: "HSI alta capacidad",
    },
    {
      brand: "Astec",
      model: "GT2310",
      feedMm: 900,
      capR: [150, 300],
      notes: "Orugas",
    },
    {
      brand: "Astec",
      model: "GT4250",
      feedMm: 1100,
      capR: [250, 450],
      notes: "Orugas",
    },
  ],
  screen: [
    {
      brand: "Terex Finlay",
      model: "683",
      decks: 2,
      area_m2: 10.1,
      capR: [100, 250],
      notes: "2 deck — versátil, orugas",
    },
    {
      brand: "Terex Finlay",
      model: "684 2-deck",
      decks: 2,
      area_m2: 14.6,
      capR: [120, 280],
      notes: "2 deck — alta producción",
    },
    {
      brand: "Terex Finlay",
      model: "684 3-deck",
      decks: 3,
      area_m2: 21.9,
      capR: [150, 300],
      notes: "3 deck — alta clasificación",
    },
    {
      brand: "Terex Finlay",
      model: "694+",
      decks: 3,
      area_m2: 28.0,
      capR: [150, 350],
      notes: "3 deck — orugas, 3 fracciones",
    },
    {
      brand: "Terex Finlay",
      model: "696 3-deck",
      decks: 3,
      area_m2: 31.1,
      capR: [180, 400],
      notes: "3 deck — gran capacidad",
    },
    {
      brand: "Powerscreen",
      model: "Warrior 1800",
      decks: 2,
      area_m2: 14.6,
      capR: [100, 480],
      notes: "2 deck",
    },
    {
      brand: "Powerscreen",
      model: "Chieftain 1700",
      decks: 2,
      area_m2: 14.4,
      capR: [120, 400],
      notes: "2 deck — fácil cambio de mallas",
    },
    {
      brand: "Powerscreen",
      model: "Chieftain 2100X",
      decks: 3,
      area_m2: 28.4,
      capR: [150, 480],
      notes: "3 deck — alta capacidad",
    },
    {
      brand: "Kleemann",
      model: "MS 703i",
      decks: 3,
      area_m2: 21.0,
      capR: [100, 309],
      notes: "3 deck — eléctrico, compacto",
    },
    {
      brand: "Kleemann",
      model: "MS 953i EVO",
      decks: 3,
      area_m2: 28.5,
      capR: [150, 441],
      notes: "3 deck — diesel-eléctrico",
    },
    {
      brand: "Sandvik",
      model: "QA331",
      decks: 2,
      area_m2: 13.0,
      capR: [120, 280],
      notes: "2 deck — sucesor de QA330 (descontinuado)",
    },
    {
      brand: "Sandvik",
      model: "QA335",
      decks: 2,
      area_m2: 24.0,
      capR: [150, 320],
      notes: "plantas áridos — Doublescreen, 2 cajas de 2 decks en serie",
    },
    {
      brand: "Metso Outotec",
      model: "ST2.4",
      decks: 2,
      area_m2: 10.8,
      capR: [100, 250],
      notes: "2 deck",
    },
    {
      brand: "Metso Outotec",
      model: "ST3.5",
      decks: 2,
      area_m2: 11.0,
      capR: [150, 350],
      notes: "capacidad por verificar, sin fuente oficial de marketing confirmada",
    },
    {
      brand: "Astec",
      model: "M6x20-3D",
      decks: 3,
      area_m2: null,
      capR: [150, 300],
      notes: "3 deck",
    },
  ],
  screen_1d: [
    {
      brand: "Terex Finlay",
      model: "Rinser 873",
      decks: 1,
      capR: [80, 200],
      notes: "1 deck lavado/descascarado",
    },
    {
      brand: "Powerscreen",
      model: "Warrior 600",
      decks: 1,
      capR: [60, 150],
      notes: "1 deck, compacta",
    },
    {
      brand: "Kleemann",
      model: "MS 402i",
      decks: 1,
      capR: [70, 180],
      notes: "1 deck eléctrico",
    },
    {
      brand: "Metso Outotec",
      model: "ST1.5",
      decks: 1,
      capR: [80, 180],
      notes: "1 deck",
    },
    {
      brand: "Sandvik",
      model: "QA141",
      decks: 1,
      capR: [80, 200],
      notes: "1 deck",
    },
  ],
  screen_hf: [
    {
      brand: "Terex Finlay",
      model: "883 HF",
      decks: 2,
      capR: [80, 200],
      notes: "Alta frecuencia 2 deck, finos",
    },
    {
      brand: "Terex Finlay",
      model: "884 HF",
      decks: 2,
      capR: [100, 240],
      notes: "Alta frecuencia 2 deck",
    },
    {
      brand: "Powerscreen",
      model: "Warrior 2100",
      decks: 2,
      capR: [100, 250],
      notes: "Alta frecuencia, fino seco",
    },
    {
      brand: "Kleemann",
      model: "MOBISCREEN HF",
      decks: 2,
      capR: [80, 200],
      notes: "Alta frecuencia",
    },
    {
      brand: "Metso Outotec",
      model: "SF Series HF",
      decks: 2,
      capR: [90, 220],
      notes: "Alta frecuencia",
    },
  ],
};

// EQ_BY_CAT se define dentro del componente App (accede al catálogo remoto vía estado).
// Esta constante local solo se usa como fallback si el componente no ha cargado aún.
export const EQ_BY_CAT_LOCAL = {
  jaw: EQ_LOCAL.jaw,
  cone: EQ_LOCAL.cone,
  hsi: EQ_LOCAL.hsi,
  screen3d: EQ_LOCAL.screen.filter((e) => e.decks === 3),
  screen2d: EQ_LOCAL.screen.filter((e) => e.decks === 2),
  screen1d: EQ_LOCAL.screen_1d,
  screen_hf: EQ_LOCAL.screen_hf,
};

export const CAT_LABELS = {
  jaw: "Mandíbula",
  cone: "Cono",
  hsi: "HSI",
  screen3d: "Selec. 3D",
  screen2d: "Selec. 2D",
  screen1d: "Selec. 1D",
  screen_hf: "Selec. AF",
};
